openvpn-server:
  restart: "always"
  image: "kylemanna/openvpn"
  ports: 
    -  "1194:1194/udp"
  volumes:
   - "ovpn-data:/etc/openvpn"
  environment:
   ALLOW: "cidr_allow 0.0.0.0/0"
  cap_add:
    - ALL

openvpn-monitor:
  restart: "always"
  image: "openvpn-monitor"
  expose:
   - "80"
  environment:
   HOST: "dockervpn_openvpn-server_1"
   PORT: "5555"
  links:
    - "openvpn-server"
